name: rephelp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fl_chart: ^0.68.0
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path_provider: ^2.1.2
  path: ^1.9.0
  table_calendar: ^3.2.0
  intl: ^0.20.2
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.2
  flutter_timezone: ^4.1.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/img/icon.png"

flutter:
  uses-material-design: true